In [26]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
x.shape

torch.Size([12])

In [28]:
x.numel()

12

In [29]:
x = x.reshape([2, 6])
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [30]:
x = x.reshape([2, 2, 3])
x
y = torch.tensor([[[2, 3, 4], [3, 4, 5]], [[2, 3, 4], [3, 4, 5]]])
y
print(torch.cat((x, y), dim=0),
torch.cat((x, y), dim=1),
torch.cat((x, y), dim=2))


tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[ 2,  3,  4],
         [ 3,  4,  5]],

        [[ 2,  3,  4],
         [ 3,  4,  5]]]) tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11],
         [ 2,  3,  4],
         [ 3,  4,  5]]]) tensor([[[ 0,  1,  2,  2,  3,  4],
         [ 3,  4,  5,  3,  4,  5]],

        [[ 6,  7,  8,  2,  3,  4],
         [ 9, 10, 11,  3,  4,  5]]])


In [31]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,100000\n')

In [37]:
a = torch.arange(3).reshape((3, 1))
#import ipdb;ipdb.set_trace()
b = torch.arange(2).reshape((1, 2))
print(a, '\n', b, '\n')
print(a + b)

--Return--
None
> /tmp/ipykernel_11330/3320012021.py(2)<module>()
      1 a = torch.arange(3).reshape((3, 1))
----> 2 import ipdb;ipdb.set_trace()
      3 b = torch.arange(2).reshape((1, 2))

--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user
tensor([[0],
        [1],
        [2]]) 
 tensor([[0, 1]]) 

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [18]:
import os
import pandas as pd
#path = '~\下载\code_vs\covid_test.csv'
data = pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  100000


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  100000

In [43]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


/home/iderea/anaconda3/envs/deep4/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


***in the table of csv, the first column is NumRooms, not 0 1 2 3, it is just used to show the table clearly and directly***

In [41]:
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
y

tensor([127500, 106000, 178100, 100000])